#!/bin/bash
set -eu -o pipefail
if [[ -n "${DEBUG:-}" ]]; then
    aws --version
    set -x
fi
aws_user=security-rapid7
export AWS_ACCESS_KEY_ID=$GH_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$GH_AWS_SECRET_ACCESS_KEY

[[ -n "${DEBUG:-}" ]] && echo "Get session token"
STS=$(aws sts get-session-token --region "eu-west-2")

AWS_ACCESS_KEY_ID=$(echo "$STS" | jq -r '.Credentials.AccessKeyId')
AWS_SECRET_ACCESS_KEY=$(echo "$STS" | jq -r '.Credentials.SecretAccessKey')
AWS_SESSION_TOKEN=$(echo "$STS" | jq -r '.Credentials.SessionToken')

export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN

[[ -n "${DEBUG:-}" ]] && echo "Assume role"
aws sts assume-role --role-arn "arn:aws:iam::720541322708:role/eks-$aws_user" --role-session-name="$aws_user-$(date +%m%d%Y)" --debug
EKS=$(aws sts assume-role --role-arn "arn:aws:iam::720541322708:role/eks-$aws_user" --role-session-name="$aws_user-$(date +%m%d%Y)")

[[ -n "${DEBUG:-}" ]] && echo "Configuring eks aws profile"
aws configure set aws_access_key_id $(echo "$EKS" | jq -r '.Credentials.AccessKeyId') --profile "$aws_user"-session-eks
aws configure set aws_secret_access_key $(echo "$EKS" | jq -r '.Credentials.SecretAccessKey') --profile "$aws_user"-session-eks
aws configure set aws_session_token $(echo "$EKS" | jq -r '.Credentials.SessionToken') --profile "$aws_user"-session-eks

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

[[ -n "${DEBUG:-}" ]] && echo "Update kubeconfig"
aws eks update-kubeconfig --name dev-cht-eks --role-arn arn:aws:iam::720541322708:role/eks-"$aws_user" --profile "$aws_user"-session-eks --region eu-west-2

kubectl get ns
